### ISSUE TITLE
missing photos on iOS Nextcloud App

### ISSUE THREAD

**Issue by nlienard** [nextcloud/ios#1663]
Issue:

iOS nextcloud is showing 242 pictures in "Media" and same in Files/Photos.
When using web browser, it shows on the bottom 9545 files as well.

To reproduce: just go to iOS nextcloud app and the amount of photos is very low.

Did multiple cache reset but same.

```
www-data@rpi4-cloud:~/nextcloud$ ./occ status
  - installed: true
  - version: 21.0.3.1
  - versionstring: 21.0.3
  - edition:
 

iOS: 14.7.1

PHP: 7.3.19-1~deb10u1
```

I also did a rescan just in case of:

```
www-data@rpi4-cloud:~/nextcloud$ ./occ files:scan  --path=nico/files/Photos
Starting scan for user 1 out of 1 (nico)
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 12      | 9540  | 00:04:48     |
+---------+-------+--------------+
```

Any tips is welcome
