### ISSUE TITLE
Cannot grant access to ios app

### ISSUE THREAD

**Issue by Horuyuki** [nextcloud/ios#2032]
### Steps to reproduce

1. Type in nextcloud domain in ios app
2. Log in
3. Click Grant Access
4. Error says it cannot be granted

### Expected behaviour

Log in to nextcloud on the ios app.

### Actual behaviour

Errors out, I needed to run the command at the end of this old issue: https://github.com/nextcloud/android/issues/4786

### Reasoning or why should it be changed/implemented?
Is there a reason why this is not added to the config.php in the image? The issue is already 3 years old.

### Environment data

**iOS version:** iOS 15.5

**Nextcloud iOS app version:** see More > Settings

4.4.0.18

**Server operating system:**
Ubuntu 20.04

**Web server:** Apache, nginx
Nginx Proxy Manager

**Database:**

Maria

**PHP version:**
Dunno

**Nextcloud version:** see Nextcloud admin page
24.0.1

Compose:
```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    network_mode: npm_default
    container_name: db

  app:
    image: nextcloud:latest
    restart: always
    ports:
      - 8080:80
    links:
      - db  
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    network_mode: npm_default
    container_name: nextcloud
```
I added latest behind nextcloud.
