### ISSUE TITLE
[Bug]: Login stuck – nextcloud app on iphone

### ISSUE THREAD

**Issue by amgschnappi** [nextcloud/ios#2946]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Unable to login to nextcloud app on iphone.
Login is stuck.
But on same iphone I can use firefox and connect and login to https://subdomain.domain.com/

### Steps to reproduce

1. Install nextcloud app on android and iphone
2. Try to connect to my https://subdomain.domain.com/ via both phones

Login from android works
Login from iphone is stuck at rotating gear icon

### Expected behavior

Login from iphone should work

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by amgschnappi** [comment]
1) I am able to login to https://nextcloud27.our-servers.de using ios app.

2) "Nextcloud Help Forum (https://help.nextcloud.com/)"
Google search is full of ios related issues. But no bug or solution.
No reply to my NC forum post.

3) https://subdomain.domain.com/ is on docker. It can be logged in via samsung app, firefox on samsung, firefox on ios. But not via ios app.

```
name: nextcloud

services:
  app:
    image: nextcloud
    restart: always
    ports:
      - 8088:80
    volumes:
      - ${EXTERNAL_PATH}:/var/www/html/data
    env_file:
      - .env
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TD}
      

```
